#!/usr/bin/env bash
#
# Installs the WordPress core PHPUnit test library for integration tests.
#
# Downloads on the host (not in the container) so the library survives
# `wp.sh reset` and is inspectable when a test fails inside WordPress's
# own bootstrap rather than ours.
#
# Idempotent: re-running with the library already present is a no-op
# unless the WordPress version changed.
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

LIB_DIR=".wp-tests-lib"
DB_NAME="wordpress_test"

wp_version="$(docker compose run --rm -T cli core version 2>/dev/null | tr -d '\r\n')"
if [ -z "$wp_version" ]; then
  echo "Could not determine the WordPress version — is the stack up? Run ./docker/wp.sh up" >&2
  exit 1
fi

if [ -f "$LIB_DIR/.version" ] && [ "$(cat "$LIB_DIR/.version")" = "$wp_version" ]; then
  echo "==> Test library already at $wp_version"
else
  echo "==> Fetching WordPress $wp_version test library"
  # Clear the contents, never the directory itself. It is bind-mounted
  # into a running container, and replacing it would allocate a new inode
  # that the existing mount does not point at — the container would go on
  # seeing the old, now-unlinked directory as empty, and the suite would
  # fail claiming the library is missing even though the host has it.
  mkdir -p "$LIB_DIR"
  find "$LIB_DIR" -mindepth 1 -delete

  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT

  curl -sSL "https://github.com/WordPress/wordpress-develop/archive/refs/tags/${wp_version}.tar.gz" \
    -o "$tmp/wp.tar.gz"

  # Only the harness and its fixtures are needed, not all of core's source.
  tar -xzf "$tmp/wp.tar.gz" -C "$tmp" \
    --strip-components=3 \
    "wordpress-develop-${wp_version}/tests/phpunit/includes" \
    "wordpress-develop-${wp_version}/tests/phpunit/data"

  mv "$tmp/includes" "$tmp/data" "$LIB_DIR/"
  echo "$wp_version" > "$LIB_DIR/.version"
fi

echo "==> Writing wp-tests-config.php"
# DB_HOST is the compose service name: this config is read from inside the
# container, never from the host.
cat > "$LIB_DIR/wp-tests-config.php" <<'PHP'
<?php
/**
 * Generated by docker/install-wp-tests.sh — do not edit by hand.
 *
 * Points WordPress's test harness at the throwaway wordpress_test
 * database, which it drops and recreates on every run. It is a separate
 * database from the one backing the dev site, so running tests never
 * touches seeded data.
 */

define( 'ABSPATH', '/var/www/html/' );
define( 'WP_TESTS_CONFIG_FILE_PATH', __FILE__ );

define( 'DB_NAME', 'wordpress_test' );
define( 'DB_USER', 'root' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST', 'db' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

$table_prefix = 'wptests_';

define( 'WP_TESTS_DOMAIN', 'example.org' );
define( 'WP_TESTS_EMAIL', 'admin@example.org' );
define( 'WP_TESTS_TITLE', 'Test Blog' );
define( 'WP_PHP_BINARY', 'php' );

define( 'WP_DEBUG', true );

define( 'AUTH_KEY', 'test-auth-key' );
define( 'SECURE_AUTH_KEY', 'test-secure-auth-key' );
define( 'LOGGED_IN_KEY', 'test-logged-in-key' );
define( 'NONCE_KEY', 'test-nonce-key' );
define( 'AUTH_SALT', 'test-auth-salt' );
define( 'SECURE_AUTH_SALT', 'test-secure-auth-salt' );
define( 'LOGGED_IN_SALT', 'test-logged-in-salt' );
define( 'NONCE_SALT', 'test-nonce-salt' );
PHP

echo "==> Ensuring $DB_NAME exists"
docker compose exec -T db \
  mariadb -uroot -pwordpress -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"

echo "Done. Run ./docker/wp.sh test"
